### ISSUE TITLE
celery worker raises exception

### ISSUE THREAD

**Issue by syonekura** [williln/celery-docker-example#1]
Hi,

I cloned this repo to try to run celery in docker but I got the exception raised because the worker is running with sudo privileges:

> usr/local/lib/python3.6/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is absolutely not recommended!

is there a way to fix this?

**Comment by MarcAstr0** [comment]
I had this exception as well. Here's the stack trace I get when running `docker-compose up`:

```
celery_1       | /usr/local/lib/python3.6/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
celery_1       | absolutely not recommended!
celery_1       |
celery_1       | Please specify a different user using the -u option.
celery_1       |
celery_1       | User information: uid=0 euid=0 gid=0 egid=0
celery_1       |
celery_1       |   uid=uid, euid=euid, gid=gid, egid=egid,
celery_1       | Traceback (most recent call last):
celery_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 123, in __getattr__
celery_1       |     return self[key]
celery_1       | KeyError: 'async'
celery_1       |
celery_1       | During handling of the above exception, another exception occurred:
celery_1       |
celery_1       | Traceback (most recent call last):
celery_1       |   File "/usr/local/bin/celery", line 11, in <module>
celery_1       |     sys.exit(main())
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
celery_1       |     _main()
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
celery_1       |     cmd.execute_from_commandline(argv)
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celery_1       |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
celery_1       |     return self.handle_argv(self.prog_name, argv[1:])
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
celery_1       |     return self.execute(command, argv)
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
celery_1       |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
celery_1       |     return self(*args, **options)
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
celery_1       |     ret = self.run(*args, **kwargs)
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
celery_1       |     **kwargs)
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
celery_1       |     self.setup_instance(**self.prepare_args(**kwargs))
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 122, in setup_instance
celery_1       |     self.should_use_eventloop() if use_eventloop is None
celery_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
celery_1       |     self._conninfo.transport.implements.async and
celery_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 125, in __getattr__
celery_1       |     raise AttributeError(key)
celery_1       | AttributeError: async
```

**Comment by williln** [comment]
Hey @syonekura @MarcAstr0 👋  

I upgraded the Celery version, which fixed the `AttributeError` for me. 

I'm investigating the `RuntimeWarning` related to using superuser privileges. I'd never noticed it before. That warning doesn't stop Celery from running, so the project still works. But I'll try to get you an answer soon on what it means and what to do about it. 

Thanks for checking out this project! I'm a Celery beginner myself so this repo is a space for me to remember how all this works. Glad it's a bit useful to others.
